services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_UID: ${UID}
                HOST_GID: ${GID}
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        networks:
            - laravel
        depends_on:
            - postgres

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    postgres:
        image: postgres:15
        container_name: laravel_postgres
        restart: always
        environment:
            POSTGRES_DB: monaco
            POSTGRES_USER: monaco_user
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

volumes:
    postgres_data:


networks:
    laravel:
        driver: bridge
